# Run the MS Internal component governance process and report the data internally.

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: ComponentGovernanceComponentDetection@0
  inputs:
    scanType: 'Register'
    verbosity: 'Verbose'
    alertWarningLevel: 'High'
  displayName: 'Component Detection'